// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _05_Fiap.Web.AspNet.Persistences;

namespace _05_Fiap.Web.AspNet.Migrations
{
    [DbContext(typeof(OlimpiadasContext))]
    partial class OlimpiadasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Campeonato", b =>
                {
                    b.Property<int>("CampeonatoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<decimal>("Premiacao");

                    b.Property<int>("TipoCampeonato");

                    b.HasKey("CampeonatoId");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.CampeonatoTime", b =>
                {
                    b.Property<int>("CampeonatoId");

                    b.Property<int>("TimeId");

                    b.HasKey("CampeonatoId", "TimeId");

                    b.HasIndex("TimeId");

                    b.ToTable("CampeonatoTime");
                });

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Jogador", b =>
                {
                    b.Property<int>("JogadorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Altura");

                    b.Property<int?>("JogadorId1");

                    b.Property<string>("Nome");

                    b.Property<int>("TimeId");

                    b.HasKey("JogadorId");

                    b.HasIndex("JogadorId1");

                    b.HasIndex("TimeId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Time", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Esporte");

                    b.Property<bool>("Mascote");

                    b.Property<string>("Nome");

                    b.Property<int>("TreinadorId");

                    b.HasKey("TimeId");

                    b.HasIndex("TreinadorId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Treinador", b =>
                {
                    b.Property<int>("TreinadorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<decimal>("Salario");

                    b.HasKey("TreinadorId");

                    b.ToTable("Treinadores");
                });

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.CampeonatoTime", b =>
                {
                    b.HasOne("_05_Fiap.Web.AspNet.Models.Campeonato", "Campeonato")
                        .WithMany("Times")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("_05_Fiap.Web.AspNet.Models.Time", "Time")
                        .WithMany("Times")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Jogador", b =>
                {
                    b.HasOne("_05_Fiap.Web.AspNet.Models.Jogador")
                        .WithMany("Jogadores")
                        .HasForeignKey("JogadorId1");

                    b.HasOne("_05_Fiap.Web.AspNet.Models.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Time", b =>
                {
                    b.HasOne("_05_Fiap.Web.AspNet.Models.Treinador", "tecnico")
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
